name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout source code ---
    - name: Checkout repo
      uses: actions/checkout@v4

    # --- Set up Python ---
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # --- Install dependencies ---
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt           # your requirements file


    # --- Start Flask app in background ---
    - name: Run Flask app
      env:
        FLASK_APP: app.py
      run: |
        nohup python app.py > flask.log 2>&1 &                   # start server
        sleep 5                          # give it a moment to boot

    # --- Run tests ---
    - name: Run pytest
      run: pytest test_app2.py -v -s
